#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SCRIPTS=(
    "auto-all"
    "auto-changed"
    "build-all"
    "build-changed"
    "push-to-repo"
    "clean-all"
    "gpg-key-set"
)

echo "############################################################"
echo "###   Do u want to clone full repo ? (or just latest ?)  ###"
echo "############################################################"
echo "1 (latest) ; 2 (full)    [default:1]"
read git_clone_type

case $git_clone_type in
    "2")
        echo -e "\n\n\ncloning full git"
        git clone --branch configs https://github.com/n0ctaneteam/N0ctOS-configs.git
        ;;
    *)
        echo -e "\n\n\ncloning latest git"
        git clone --depth=1 --branch configs https://github.com/n0ctaneteam/N0ctOS-configs.git
        ;;
esac

for FILE in "${SCRIPTS[@]}"; do
    chmod +x "$SCRIPT_DIR/$FILE"
    echo "chmod-ed $FILE"
done

echo -e "\n\n\n\n\n\   Setup GH-CLI"
sudo pacman -Sy github-cli --needed --noconfirm

gh auth login

echo
echo "########################################"
echo "!!!        Dev Env setup done        !!!"
echo "########################################"
echo -e "\n\n"
echo -e "Read the docs for more info"
echo "https://n0ctaneteam.github.io/N0ctOS"
